config/routes.rb
Rails.application.routes.draw do

  resources :users
  get "users/new"

  get "/about",to: 'about#index'
  get "/about/contact",to: 'about#contact'

  root :to =>"users#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def contact
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :status)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/contact.html.erb
<h1> Contact pages goes here </h1>

app/views/about/index.html.erb
<!DOCTYPE HTML>
<html>

<head>
    <title>Latihan Javascript</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:200,500,600,800,900i&amp;subset=latin-ext" rel="stylesheet">
    <meta charset="utf-8">
</head>

<body>
    <div class="container-fluid">
        <div id="section-atas">
            <div id="row">
                <h1 class="center about">ABOUT</h1>
                <div id="col-lg">
                    <p class="desc"><span class="aiosewa">AioSewa</span> merupakan salah satu online marketplace yang menyediakan sarana sewa-menyewa yang aman dan terpercaya antara vendor penyedia barang maupun jasa dan event dengan konsumennya.</p>
                </div>
                <p class="desc"><span class="aiosewa">AioSewa</span> memberikan jaminan 100% uang kebali kepada penyewa jika ada vendor yang merugikan. Dalam platform ini konsumen diberikan berbagai macam perlengkapan dan jasa perlu disiapkan untuk menghelat suatu acara
                    dengan harga yang relatif sesuai dengan kantong.</p>

                <!-- 3 line gaje -->
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div id="section-bawah">
            <h1 class="center team">The Team</h1>
            <div class="row">
                <div class="col-md">
                    <div class="name">Try Wiguna</div>
                    <div class="pangkat">CEO</div>
                    <%= image_tag("tw.png", :alt => "tw" , :class => "img-fluid") %>
                </div>
                <div class="col-md">
                    <div class="name">Bagus Prasetyo</div>
                    <div class="pangkat">CTO</div>
                    <%= image_tag("bagus.png", :alt => "bagus", :class=>"img-fluid") %>
                </div>
            </div>
            <div class="row">
                <div class="col-md">
                    <%= image_tag("yoga.png", :alt => "yoga",:class=>"img-fluid") %>
                        <div class="name">Komang Yogananda</div>
                        <div class="pangkat">COO</div>
                </div>
                <div class="col-md">
                    <%= image_tag("tiago.png", :alt => "tiago",:class=>"img-fluid") %>
                        <div class="name">Kadek Tiago</div>
                        <div class="pangkat">CPO</div>
                </div>
            </div>
        </div>
    </div>
    <br style="clear:both;">
    <div class="container-fluid footer">
        <p class="center footer">Keep In Touch With Us!</p>

        <div class="icon">
            <a href="https://www.facebook.com"><%= image_tag("fb.png", :alt =>"facebook", :class=>"img-fluid")%></a>
        </div>

        <div class="icon">
            <a href="https://line.com"><img class="imgcenter" src="line.png" alt="line"></a>
        </div>

        <div class="icon">
            <a href="https://www.instagram.com"><img class="imgcenter" src="ig.png" alt="instagram"></a>
        </div>

        <div class="icon">
            <a href="https://www.youtube.com"><img class="imgcenter" src="ytb.png" alt="youtube"></a>
        </div>

        <br style="clear:both;">

    </div>
    </div>

</body>


</html>
<%= link_to 'Contact', about_contact_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Xevent</title>
    <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
                <link href="https://fonts.googleapis.com/css?family=Lora|Roboto+Slab:100" rel="stylesheet">
                <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">



</head>

<body>
    <%= yield %>
</body>

</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                        </div>
                        <div class="modal-body text-center">
                            <div class="field">
                                <%= form.label :email %>
                                    <%= form.text_field :email, id: :user_email %><br/>
                                        <%= form.label :status %>
                                            <%= form.radio_button :status, 'VENDOR' %> Vendor
                                                <%= form.radio_button :status, 'CUSTOMER' %> Customer <br />
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= form.submit "Submit", class:"btn btn-primary"%>
                        </div>
                    </div>
                </div>
            </div>




            <div class="actions">
            </div>
            <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice">
    <%= notice %>
</p>

<h1>Users</h1>

<table>
    <thead>
        <tr>
            <th>Email</th>
            <th>Status</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td>
                    <%= user.email %>
                </td>
                <td>
                    <%= user.status %>
                </td>
                <td>
                    <%= link_to 'Show', user %>
                </td>
                <td>
                    <%= link_to 'Edit', edit_user_path(user) %>
                </td>
                <td>
                    <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
            </tr>
            <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container mt-3 h-100">
    <div class="row pt-5">
        <div class="col-lg-12 col-md-6 tex-center">
            <h1 class="text-center">AioEvent</h1>
        </div>
    </div>

    <div class="row pt-5">
        <div class="col-lg-6 pt-4 img">
            <%= image_tag('Zoobirthday.jpg', class: 'img-fluid') %>
        </div>
        <div class="col-lg-6 pt-4">
            <p class="jargon pt-0">Siapapun bisa membuat event impiannya dengan mudah</p>
            <p class="jargon-2 pt-3">Buat eventmu dengan para EO terpercaya di AioEvent</p>
            <div class="col-lg-12 text-center pt-4">
                <button type="button" class="btn btn-primary buttonBox" data-toggle="modal" data-target="#exampleModalCenter">Saya tertarik</button>
            </div>
        </div>

        <%= render 'form', user: @user %>
    </div>

    <div class="row pt-5 text-center">
        <div class="col-md-4">
            <i class="fas fa-handshake" style="font-size:2.5rem"></i>
            <h3>Lorem Ipsum</h3>
            <p class="text-left"> Shabby chic put a bird on it seitan, chartreuse activated charcoal gochujang four dollar toast mumblecore chambray umami shoreditch +1 readymade whatever 8-bit. Squid etsy scenester farm-to-table. Tattooed tousled cray +1 ugh, etsy sustainable
                flexitarian vexillologist actually.</p>
        </div>
        <div class="col-md-4">
            <i class="fas fa-birthday-cake" style="font-size:2.5rem"></i>
            <h3>Lorem Ipsum</h3>
            <p class="text-left"> Shabby chic put a bird on it seitan, chartreuse activated charcoal gochujang four dollar toast mumblecore chambray umami shoreditch +1 readymade whatever 8-bit. Squid etsy scenester farm-to-table. Tattooed tousled cray +1 ugh, etsy sustainable
                flexitarian vexillologist actually.</p>
            </p>
        </div>
        <div class="col-md-4">
            <i class="fas fa-gift" style="font-size:2.5rem"></i>
            <h3>Lorem Ipsum</h3>
            <p class="text-left"> Shabby chic put a bird on it seitan, chartreuse activated charcoal gochujang four dollar toast mumblecore chambray umami shoreditch +1 readymade whatever 8-bit. Squid etsy scenester farm-to-table. Tattooed tousled cray +1 ugh, etsy sustainable
                flexitarian vexillologist actually.</p>
            </p>
        </div>
    </div>
</div>


<!-- <%= link_to 'Back', users_path %>
    <%= link_to 'About',about_path%> -->

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>